server:
  port: 8000
  ssl:
    enabled: false
    bundle: "secureme-gateway"
    enabled-protocols: TLSv1.3
spring:
  application:
    name: secure-me-gateway
  ssl:
    enabled: true
    bundle:
      jks:
        secureme-gateway:
          key:
            alias: "secureme-gateway"
          keystore:
            location: "classpath:secureme-gateway.jks"
            password: "secureme-gateway"
            type: "JKS"
            provider: "SUN"
          truststore:
            location: "classpath:secureme-gateway.jks"
            password: "secureme-gateway"
            type: "JKS"
  profiles:
    active:
    - dev
  config:
    import:
    - optional:configserver:https://config:config@localhost:8888
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
        - Path=/user/authentication/**
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
          - Path=/user/register/**
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
          - Path=/roles
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
          - Path=/user/validateToken/**
        filters:
          - AuthorizationFilter
      - id: SECURE-ME-METADATA
        uri: lb://SECURE-ME-METADATA
        predicates:
          - Path=/metadata/**
        filters:
          - AuthorizationFilter

          
          
    
