server:
  port: 8000
spring:
  application:
    name: secure-me-gateway
  profiles:
    active:
    - dev
  config:
    import:
    - optional:configserver:http://config:config@localhost:8888
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
        - Path=/user/authentication/**
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
          - Path=/user/register/**
      - id: SECURE-ME-AUTHENTICATION
        uri: lb://SECURE-ME-AUTHENTICATION
        predicates:
          - Path=/user/validateToken/**
        filters:
          - AuthorizationFilter
      - id: SECURE-ME-METADATA
        uri: lb://SECURE-ME-METADATA
        predicates:
          - Path=/metadata/**
        filters:
          - AuthorizationFilter

          
          
    
